name: "publish release - GitHub Packages"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 5 * * *"
  push:
    branches:
      - release-*
  release:
    types: [published]

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  publish-npm:
    name: "publish NPM packages to GitHub Packages"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.repository_owner }}'
    - run: npm ci
    - run: npm run build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "@next: publish with commit timestamp (triggered manually)"
      if: contains(github.ref, 'main') && github.event_name == 'workflow_dispatch'
      run: |
        node utils/build/update_canary_version.js --alpha --commit-timestamp
        utils/publish_all_packages.sh --alpha
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "@next: publish with today's date (triggered automatically)"
      if: contains(github.ref, 'main') && github.event.schedule
      run: |
        node utils/build/update_canary_version.js --alpha --today-date
        utils/publish_all_packages.sh --alpha
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "@beta: publish with commit timestamp (triggered automatically)"
      if: contains(github.ref, 'release') && github.event_name == 'push'
      run: |
        node utils/build/update_canary_version.js --beta --commit-timestamp
        utils/publish_all_packages.sh --beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "publish release"
      if: github.event_name == 'release' && github.event.action == 'published'
      run: utils/publish_all_packages.sh --release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
