name: "publish release - GitHub Packages"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  release:
    types: [published]

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  publish-packages:
    name: "publish to GitHub Packages"
    runs-on: ubuntu-24.04
    if: github.repository == 'iceteagroup-testmanager/playwright'
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        scope: '@iceteagroup-testmanager'
    - run: npm ci
    - run: npm run build

    - name: "publish packages"
      if: github.event_name == 'release' && github.event.action == 'published'
      run: utils/publish_all_packages.sh --release
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
